service: my-test-service

plugins:
  - serverless-restapi-automatic-deployment

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: GET
